"""ClawNix MCP server for document creation (PPTX, XLSX, PDF)."""

import json
import os
from datetime import datetime

from fastmcp import FastMCP
from openpyxl import Workbook
from pptx import Presentation
from pptx.util import Inches, Pt
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer

mcp = FastMCP(
    name="clawnix-mcp-documents",
    instructions="Create PPTX presentations, XLSX spreadsheets, and PDF documents.",
)


def _output_dir() -> str:
    d = os.environ.get("CLAWNIX_DOCUMENTS_DIR", "/tmp/clawnix-documents")
    os.makedirs(d, exist_ok=True)
    return d


def _timestamp() -> str:
    return datetime.now().strftime("%Y%m%d-%H%M%S")


@mcp.tool
def create_presentation(title: str, slides: list[dict]) -> str:
    """Create a PowerPoint presentation.

    Each slide dict should have 'title' (str) and 'content' (str) keys.
    Returns JSON with file path and metadata.
    """
    prs = Presentation()

    # Title slide
    layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(layout)
    slide.shapes.title.text = title
    if slide.placeholders[1]:
        slide.placeholders[1].text = "Generated by ClawNix"

    # Content slides
    layout = prs.slide_layouts[1]
    for s in slides:
        slide = prs.slides.add_slide(layout)
        slide.shapes.title.text = s.get("title", "")
        if slide.placeholders[1]:
            slide.placeholders[1].text = s.get("content", "")

    filename = f"{_timestamp()}-{title.replace(' ', '_')[:30]}.pptx"
    filepath = os.path.join(_output_dir(), filename)
    prs.save(filepath)

    return json.dumps({
        "status": "created",
        "file": filepath,
        "slides": len(slides) + 1,
        "title": title,
    })


@mcp.tool
def create_spreadsheet(name: str, sheets: dict[str, list[list]]) -> str:
    """Create an Excel spreadsheet.

    sheets is a dict of sheet_name -> list of rows. Each row is a list of cell values.
    Returns JSON with file path and metadata.
    """
    wb = Workbook()
    # Remove default sheet
    wb.remove(wb.active)

    for sheet_name, rows in sheets.items():
        ws = wb.create_sheet(title=sheet_name[:31])  # Excel limits to 31 chars
        for row in rows:
            ws.append(row)

    if not sheets:
        wb.create_sheet(title="Sheet1")

    filename = f"{_timestamp()}-{name.replace(' ', '_')[:30]}.xlsx"
    filepath = os.path.join(_output_dir(), filename)
    wb.save(filepath)

    return json.dumps({
        "status": "created",
        "file": filepath,
        "sheets": max(len(sheets), 1),
        "name": name,
    })


@mcp.tool
def create_pdf(title: str, content: str) -> str:
    """Create a PDF document from text content.

    Content can include newlines for paragraph breaks.
    Returns JSON with file path and metadata.
    """
    filename = f"{_timestamp()}-{title.replace(' ', '_')[:30]}.pdf"
    filepath = os.path.join(_output_dir(), filename)

    doc = SimpleDocTemplate(filepath, pagesize=A4)
    styles = getSampleStyleSheet()
    story = []

    # Title
    story.append(Paragraph(title, styles["Title"]))
    story.append(Spacer(1, 12))

    # Content paragraphs
    for paragraph in content.split("\n\n"):
        paragraph = paragraph.strip()
        if paragraph:
            story.append(Paragraph(paragraph, styles["BodyText"]))
            story.append(Spacer(1, 6))

    doc.build(story)

    return json.dumps({
        "status": "created",
        "file": filepath,
        "title": title,
    })


def main():
    mcp.run()


if __name__ == "__main__":
    main()
